### ISSUE TITLE
Plugin does not start even with it on the server

### ISSUE THREAD

**Issue by crashzk** [skaen/Auto-Map-Changer#3]
I installed everything correctly but the plugin does not load, better yet, it loads with another name as you can see in the screenshot.

![image](https://github.com/skaen/Auto-Map-Changer/assets/32937653/113523e5-60a5-4345-98ac-5702620716ff)

Yes, I installed Auto Map Changer as you can see, the **Weapon Restrict** plugin wasn't even installed.
![image](https://github.com/skaen/Auto-Map-Changer/assets/32937653/55e0b06a-711f-41f9-bdd7-1ae18d241bf3)

When I remove the `AutoChangeMap` folder from the plugin list, **Weapon Restrict** comes out too.

**Comment by skaen** [comment]
https://github.com/skaen/Auto-Map-Changer/releases/tag/1.0.6

**Comment by crashzk** [comment]
Fix
