### ISSUE TITLE
add option to ignore the bots

### ISSUE THREAD

**Issue by mayersgamer** [skaen/Auto-Map-Changer#5]
add option to not count the bots , so if there is 2 bots in server the map will be changed anyway to default

**Comment by skaen** [comment]
> add option to not count the bots , so if there is 2 bots in server the map will be changed anyway to default

Please enable `debug` in the config and show what `Players count` outputs?

**Comment by skaen** [comment]
https://github.com/skaen/Auto-Map-Changer/releases/tag/1.0.9

**Comment by mayersgamer** [comment]
what do you mean change map even if there is no players ? i want the plugin to change the map back to mirage when server is empty of real players but my server is always with 2 bots present , so is this plugin ignoring bots or counting them as players ?

**Comment by skaen** [comment]
@mayersgamer  

If the parameter `ChangeMap` = false, and `DefaultMap` has the value `de_dust2`, while the map on the server is `de_dust2` - the command `map de_dust2` will not be executed.

If the parameter `ChangeMap` = true, the command `map de_dust2` will be executed every time the timer expires when there are no players on the server.

The player count does not include bots in the game; it only counts real players:
`Utilities.GetPlayers().Where(controller => controller is { IsValid: true, IsBot: false, IsHLTV: false })`
