### ISSUE TITLE
[REQ] Option to enable/disable whether to change to the same map

### ISSUE THREAD

**Issue by crashzk** [skaen/Auto-Map-Changer#6]
I have set `de_mirage` as the default map, but I would like to change it to it even if the server does not have a player connecting to it for X amount of time.

In other words, even if it is mirage, and the server has no players connecting after 8 hours, it switches to the mirage map again.

It would be useful because if the server stays online for more than 12 hours on the same map it starts to suffer from lag and the game freezes.

**Comment by skaen** [comment]
@crashzk https://github.com/skaen/Auto-Map-Changer/releases/tag/1.0.9
